"""PDF report generation for InfraSphere."""
from __future__ import annotations

import io
from fpdf import FPDF

from app.data.regions import get_regions
from app.data.securities import get_securities, CATEGORY_LABELS
from app.services.insights import get_insights


def _clean(text: str) -> str:
    """Sanitise to Latin-1 safe characters."""
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_report() -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Title page ───────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.cell(0, 60, _clean("InfraSphere"), ln=True, align="C")
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, _clean("AI Infrastructure & Power Grid Convergence Report"), ln=True, align="C")
    pdf.cell(0, 8, _clean("Generated by InfraSphere Platform"), ln=True, align="C")
    pdf.ln(20)

    # ── Insights ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _clean("Key Insights"), ln=True)
    pdf.ln(4)

    insights = get_insights()
    pdf.set_font("Helvetica", "", 10)
    for ins in insights[:10]:
        severity_icon = {"critical": "[!]", "warning": "[W]", "opportunity": "[+]", "info": "[i]"}.get(ins.severity, "")
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, _clean(f"{severity_icon} {ins.title}"), ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _clean(ins.description))
        if ins.tickers:
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 5, _clean(f"  Tickers: {', '.join(ins.tickers)}"), ln=True)
        pdf.ln(3)

    # ── Regional Grid Summary ────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _clean("Regional Grid Summary"), ln=True)
    pdf.ln(4)

    regions = get_regions()
    pdf.set_font("Helvetica", "B", 8)
    col_w = [50, 22, 22, 22, 22, 22, 22]
    headers = ["Region", "Cap (GW)", "Demand", "AI (GW)", "AI Gr%", "Strain", "Price"]
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 6, _clean(h), border=1, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for r in regions:
        pdf.cell(col_w[0], 5, _clean(r["name"][:28]), border=1)
        pdf.cell(col_w[1], 5, f"{r['grid_capacity_gw']:.0f}", border=1, align="R")
        pdf.cell(col_w[2], 5, f"{r['current_demand_gw']:.0f}", border=1, align="R")
        pdf.cell(col_w[3], 5, f"{r['ai_demand_gw']:.1f}", border=1, align="R")
        pdf.cell(col_w[4], 5, f"{r['ai_demand_growth_pct']}%", border=1, align="R")
        pdf.cell(col_w[5], 5, f"{r['grid_strain_index']:.0%}", border=1, align="R")
        pdf.cell(col_w[6], 5, f"${r['avg_electricity_price_kwh']:.3f}", border=1, align="R")
        pdf.ln()

    # ── Securities Overview ──────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _clean("Infrastructure Securities"), ln=True)
    pdf.ln(4)

    securities = get_securities()
    pdf.set_font("Helvetica", "B", 8)
    sec_cols = [16, 42, 28, 22, 18, 18, 22, 18]
    sec_headers = ["Ticker", "Name", "Category", "MCap $B", "YTD%", "AI Rev%", "Pwr Sens", "ESG"]
    for i, h in enumerate(sec_headers):
        pdf.cell(sec_cols[i], 6, _clean(h), border=1, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    for s in securities:
        cat_label = CATEGORY_LABELS.get(s["category"], s["category"])[:16]
        pdf.cell(sec_cols[0], 5, s["ticker"], border=1)
        pdf.cell(sec_cols[1], 5, _clean(s["name"][:24]), border=1)
        pdf.cell(sec_cols[2], 5, _clean(cat_label), border=1)
        pdf.cell(sec_cols[3], 5, f"{s['market_cap_bn']:.0f}", border=1, align="R")
        pdf.cell(sec_cols[4], 5, f"{s['ytd_return']:+.0f}%", border=1, align="R")
        pdf.cell(sec_cols[5], 5, f"{s['ai_infra_revenue_pct']}%", border=1, align="R")
        pdf.cell(sec_cols[6], 5, f"{s['power_demand_sensitivity']:.2f}", border=1, align="R")
        pdf.cell(sec_cols[7], 5, f"{s['esg_score']}", border=1, align="R")
        pdf.ln()

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.ln(10)
    pdf.cell(0, 5, _clean("InfraSphere | Created by Nhat Nguyen | Data as of March 2026"), align="C")

    return bytes(pdf.output())
